apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: client-server-re
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: client-server-re
    app.kubernetes.io/part-of: cli
  name: client-server-re
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: client-server-re
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: client-server-re
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-re@sha256:7360c59ea10392b288e0551c123e9f0bea824a535ebbf512b9fe543265788f77
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
