apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: client-server-cg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: client-server-cg
    app.kubernetes.io/part-of: cli
  name: client-server-cg
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: client-server-cg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: client-server-cg
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-cg@sha256:38df3f8bb8f5e89bd06e53ee20bb429e8b0f313117c35112b2c16595235b71c0
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
