apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cosign
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/cosign@sha256:4d47a96d44efc1dba028646849e131a5da9e45a5dfc5d08316249c6b45d0fead
        name: my-go
        resources: {}
status: {}
