apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client-server-re
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-re@sha256:fbba3e688085712340bf3c2801460caf83e9ab95f7747a35167f8eccf80a986b
        name: my-go
        resources: {}
status: {}
