apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client-server-re
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-re@sha256:9c4867018453a2d02be004b392b8b17e1cdb89ed841aefe619b63627f024ff90
        name: my-go
        resources: {}
status: {}
