apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gitsign
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/gitsign@sha256:d592489bfc858287c54ed5456790ec52e50df2fe6e1028d89c3d56b4cc6e0bd4
        name: my-go
        resources: {}
status: {}
