apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gitsign
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/gitsign@sha256:7de6a73c85a0f4d49b2a1ec6e96d65e41c472ac45f4fc05381bdf71299b3f594
        name: my-go
        resources: {}
status: {}
