apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gitsign
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitsign
    app.kubernetes.io/part-of: cli
  name: gitsignps3p
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gitsign
    weight: null
status: {}
