apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client-server-cg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-cg@sha256:42c98f522b171c48834bb6ddefd3fb07ad2a2505b56304dead8fc87684c1c116
        name: my-go
        resources: {}
status: {}
