apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client-server-cg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-cg@sha256:51fc639aee27cc48ccf7a694403b3f824b635191798c9d68b7e0ef322ad926bc
        name: my-go
        resources: {}
status: {}
