apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: client-server-cg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-cg@sha256:05bb13e6d02b4dc107bb651e82534fa832267fe34c859781a9909147df193ad6
        name: my-go
        resources: {}
status: {}
