apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: client-server-cg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: client-server-cg
    app.kubernetes.io/part-of: cli
  name: client-server-cgkyng
spec:
  path: /
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: client-server-cg
    weight: null
status: {}
